version: '3.5'
services:
  pnews-test:
    image: aabor/nbdatascience
    environment:
      - TZ="Europe/Kiev"
    volumes:
      - $PWD:/home/jovyan/work/nginx-flask-plumber
    working_dir: /home/jovyan/work/nginx-flask-plumber
    command: bash -c "pwd && pytest --junitxml test-reports/pnews.xml pnews/test_pnews.py"
    networks: 
      - front-end
  rnews-test:
    image: aabor/rbase-finance
    environment:
      - TZ="Europe/Kiev"
    volumes:
      - $PWD:/home/tester/nginx-flask-plumber
      - $PWD/test-reports:/home/tester/nginx-flask-plumber/rnews/tests/testthat/test-reports:rw      
    working_dir: /home/tester/nginx-flask-plumber
    command: bash -c "pwd && Rscript --verbose rnews/tests/run-tests.R"
    networks: 
      - front-end
networks: 
    front-end:
      external: true
