version: '3.5'
services:
  nginx-nfp:
      image: aabor/nginx-nfp
      build:
        context: nginx/.
      ports:
      - "80:80"
      volumes:
      - /home/$USER/R/nginx-flask-plumber/nginx-flask-plumber.log:/home/www/server.log
      restart: always
      depends_on:
      - pnews
      - rnews
      networks: 
        - back-end
  pnews: 
    image: aabor/pnews
    build: 
      context: pnews/.
    volumes:
      - /home/$USER/R/nginx-flask-plumber:/home/jovyan/work/R/nginx-flask-plumber
      - /home/$USER/Documents/Trading/fh_data-dev:/home/jovyan/work/R/nginx-flask-plumber/data
      - /home/$USER/Dropbox/mt4/data-dev:/home/jovyan/work/R/nginx-flask-plumber/data/mt4
      - /home/$USER/Documents/Trading/news-arch:/home/jovyan/nginx-flask-plumber/data/news-arch
      - /home/$USER/.ssh:/home/jovyan/.ssh/  
      - /home/$USER/.secrets:/home/jovyan/.secrets/  
      - /home/$USER/.httr-oauth:/home/jovyan/.httr-oauth
    restart: "on-failure:30"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
      - WERKZEUG_DEBUG_PIN=off
    networks: 
      - selenium-hub
      - front-end
      - back-end
  rnews: 
    image: aabor/rnews
    build: 
      context: rnews/.
    volumes:
      - /home/$USER/R/nginx-flask-plumber:/home/docker/nginx-flask-plumber
      - /home/$USER/Documents/Trading/fh_data-dev:/home/docker/nginx-flask-plumber/data
#      - /home/$USER/Dropbox/mt4/data-dev:/home/docker/fh/data/mt4
#      - /home/$USER/Documents/Trading/news-arch:/home/docker/fh/data/news-arch
      - /home/$USER/.ssh:/home/docker/.ssh/  
      - /home/$USER/.secrets:/home/docker/.secrets/  
      - /home/$USER/.httr-oauth:/home/docker/.httr-oauth
    restart: "on-failure:30"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
    networks: 
      - back-end
      - front-end
networks:
  back-end:
  selenium-hub:
    external: true
  front-end:
    external: true

