version: '3.5'
services:
#https://github.com/SeleniumHQ/docker-selenium
version: '3'
services:
  selenium-hub:
    image: selenium/hub:3.141.59-dubnium
    environment:
      - GRID_MAX_SESSION=15
      - GRID_TIMEOUT=180000
      - GRID_BROWSER_TIMEOUT=180000      
    networks: 
      - selenium-hub
  chrome:
    image: selenium/node-chrome:3.141.59-dubnium
    shm_size: 512MB
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=6
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - DBUS_SESSION_BUS_ADDRESS=/dev/null
    networks: 
      - selenium-hub
  nginx-nfp:
      image: $USER/nginx-nfp
      build:
        context: nginx/.
      ports:
      - "80:80"
      volumes:
        - $PWD/nginx-flask-plumber.log:/home/www/server.log
      restart: always
      depends_on:
      - pnews
      - rnews
      networks: 
        - back-end
  pnews: 
    image: $USER/pnews
    build: 
      context: pnews/.
    volumes:
      - $PWD/nginx-flask-plumber.log:/home/jovyan/nginx-flask-plumber/nginx-flask-plumber.log
    restart: "on-failure:30"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
      - WERKZEUG_DEBUG_PIN=off
    networks: 
      - selenium-hub
      - front-end
      - back-end
  rnews: 
    image: $USER/rnews
    build: 
      context: rnews/.
    volumes:
      - $PWD/nginx-flask-plumber.log:/home/rstudio/nginx-flask-plumber/nginx-flask-plumber.log
    restart: "on-failure:30"
    environment:
      - TZ="Europe/Kiev"
      - GIT_VERSION=$GIT_VERSION
    networks: 
      - back-end
      - front-end
networks:
  back-end:
  selenium-hub:
    external: true
  front-end:
    external: true

