library('testthat')
wd<-getwd()
output_file<-file.path(wd, "rnews/tests/testthat/test-reports/rnews.xml")
options(testthat.output_file = output_file)
#options(testthat.output_file = "")
testthat::test_dir('rnews/tests/testthat', reporter = "junit")
