pipeline {
    agent any
    environment {
        USER=credentials('jenkins-current-user')
    }    
    stages {
        stage('Developer'){
            steps {
                sh'''
                echo "Changing permissions for test reports"
                chmod 777 pnews/test-reports
                chmod 777 rnews/tests/testthat/test-reports
                '''
                echo 'Testing'
                sh '''
                    docker-compose down
                    export GIT_VERSION=$(git describe --tags | sed s/v//)
                    docker-compose -f docker-compose.yml up -d
                    docker-compose -f docker-compose.test.yml  up rnews-test
                    docker-compose -f docker-compose.test.yml  up pnews-test
                '''
            }
        }
        stage('Functional tests') {
            steps {
                echo 'Testing'
                sh '''
                    export GIT_VERSION=$(git describe --tags | sed s/v//)
                '''
            }
            post {
                always{
                    junit '**/test-reports/*.xml'
                    cleanWs()
                    sh '''
                        pwd
                        ls
                        echo "Finishing.."
                    '''
                }
            }
        }
    }
}
